# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

def sum_even(nums)
  nums.select { |n| n.even? }.inject(&:+)
end

def fibonacci_to(n)
  def fib_loop(n, nums=[1,2])
    next_num = nums[-1] + nums[-2]
    return nums if next_num > n
    fib_loop(n, nums << next_num)
  end

  fib_loop n
end
